### PR TITLE
Upgrade umbraco to latest.

### PR DESCRIPTION
**Pull request by t1er**
regarding this issue: https://our.umbraco.org/projects/backoffice-extensions/umbraco-relation-editor/general/86647-method-not-found-error

### CODE REVIEW

**Comment by lars-erik** [comment]
Did you test the site like this? I'm getting type version exceptions.
Looking into it now, but not sure I get it right right away.

**Comment by lars-erik** [comment]
I think it's due to the fact that I inherit IAction to add actions to the menus. It'll have to be rewritten to use the non-action dependent methods to add menu items. I'll get back to it. But it means there's no new version today. Sorry. Thanks again for your effort.

**Comment by t1er** [comment]
@lars-erik it would be great if you can provide new version by the end of July. I need this plugin for hreflangs implementation for multilingual sites. Thanks!

**Comment by lars-erik** [comment]
Can't promise anything, sorry. You could always look into the relation editor in nupickers if it's critical.

**Comment by lars-erik** [comment]
Thanks to @ElBart00, here's a version compatible with both. :)

https://www.nuget.org/packages/Umbraco.RelationEditor/1.2.3

**Pull request merged**
